// lib/provisioning/states.ts
export type ProvisionState =
  | 'INIT'
  | 'GITHUB_CREATING'
  | 'SUPABASE_CREATING'
  | 'SUPABASE_READY'
  | 'SCHEMA_MIGRATED'
  | 'AUTH_CONFIGURED'
  | 'STORAGE_READY'
  | 'VERCEL_CREATING'
  | 'VERCEL_DEPLOYING'
  | 'STRIPE_CUSTOMER_CREATING'
  | 'STRIPE_SUBSCRIPTION_CREATING'
  | 'COMPLETE'
  | 'FAILED';

export const ALLOWED_TRANSITIONS: Record<
  ProvisionState,
  ProvisionState[]
> = {
  INIT: ['GITHUB_CREATING'],
  GITHUB_CREATING: ['SUPABASE_CREATING'],
  SUPABASE_CREATING: ['SUPABASE_READY'],
  SUPABASE_READY: ['SCHEMA_MIGRATED'],
  SCHEMA_MIGRATED: ['AUTH_CONFIGURED'],
  AUTH_CONFIGURED: ['STORAGE_READY'],
  STORAGE_READY: ['VERCEL_CREATING'],
  VERCEL_CREATING: ['VERCEL_DEPLOYING'],
  VERCEL_DEPLOYING: ['STRIPE_CUSTOMER_CREATING'],
  STRIPE_CUSTOMER_CREATING: ['STRIPE_SUBSCRIPTION_CREATING'],
  STRIPE_SUBSCRIPTION_CREATING: ['COMPLETE'],
  COMPLETE: [],
  FAILED: [],
};

