
export type ProvisionState =
  | 'INIT'
  | 'SUPABASE_CREATING' | 'SUPABASE_VERIFYING' | 'SUPABASE_READY'
  | 'GITHUB_CREATING' | 'GITHUB_VERIFYING' | 'GITHUB_READY'
  | 'VERCEL_CREATING' | 'VERCEL_VERIFYING' | 'VERCEL_DEPLOYING' | 'VERCEL_READY'
  | 'SANDRA_CREATING' | 'SANDRA_VERIFYING' | 'SANDRA_READY'
  | 'KIRA_CREATING' | 'KIRA_VERIFYING' | 'KIRA_READY'
  | 'WEBHOOK_REGISTERING' | 'WEBHOOK_VERIFYING'
  | 'COMPLETE'
  | 'FAILED';
