// lib/lifecycle/tenantLifecycle.ts

export type TenantLifecycleState =
  | 'VISITOR'
  | 'CUSTOMER_CREATED'
  | 'AUTHENTICATED'
  | 'COMPANY_PROFILE_COMPLETE'
  | 'PERSONAL_PROFILE_COMPLETE'
  | 'AGENT_PROFILE_COMPLETE'
  | 'INTERVIEW_CONFIGURED'
  | 'ACTIVE';

export const TENANT_TRANSITIONS: Record<
  TenantLifecycleState,
  readonly TenantLifecycleState[]
> = {
  VISITOR: ['CUSTOMER_CREATED'],
  CUSTOMER_CREATED: ['AUTHENTICATED'],
  AUTHENTICATED: ['COMPANY_PROFILE_COMPLETE'],
  COMPANY_PROFILE_COMPLETE: ['PERSONAL_PROFILE_COMPLETE'],
  PERSONAL_PROFILE_COMPLETE: ['AGENT_PROFILE_COMPLETE'],
  AGENT_PROFILE_COMPLETE: ['INTERVIEW_CONFIGURED'],
  INTERVIEW_CONFIGURED: ['ACTIVE'],
  ACTIVE: [],
} as const;
